-- REF https://www.cathaybk.com.tw/cathaybk/personal/product/deposit/currency-billboard/#currencyconverter
-- 幣別與其對應中文表
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('新臺幣','TWD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('美元','USD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('歐元','EUR');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('日圓','JPY');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('人民幣','CNY');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('港幣','HKD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('澳大利亞幣','AUD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('紐西蘭幣','NZD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('南非幣','ZAR');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('加拿大幣','CAD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('英鎊','GBP');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('瑞士法郎','CHF');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('瑞典幣','SEK');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('新加坡幣','SGD');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('泰國幣','THB');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('丹麥幣','DKK');
INSERT INTO CURRENCY_NAME(CHINESE_TRADITIONAL , CODE)values('土耳其里拉','TRY');