-- 幣別與其對應中文表
CREATE TABLE CURRENCY_NAME  (
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CHINESE_TRADITIONAL VARCHAR(10) NOT NULL,
	CODE CHAR(3) NOT NULL,
	CONSTRAINT CODE_UN UNIQUE (CODE),
	CONSTRAINT CHINESE_TRADITIONAL_UN UNIQUE (CHINESE_TRADITIONAL)
);
